requirements:
- name: hcloud
  version: v1.20.0 # renovate: datasource=github-releases depName=hetznercloud/cli versioning=regex:^v(?<major>\d+?)\.(?<minor>\d+?)\.(?<patch>\d+?)(-(?<prerelease>.+?))?$
