#cloud-config

apt:
  conf: |
    APT {
      Install-Recommends "false";
      Install-Suggests "false";
      Get {
        Assume-Yes "true";
        Fix-Broken "true";
      };
    };

package_update: true
package_upgrade: true
packages:
- bash
- curl
- ca-certificates
- jq
- libcap2-bin
- libcap-ng-utils
- util-linux
- git
- make
- unzip
- sshfs

runcmd:
- sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=1"/' /etc/default/grub
- update-grub
- curl -sSLfo /tmp/uniget_Linux_x86_64.tar.gz https://github.com/uniget-org/cli/releases/latest/download/uniget_Linux_x86_64.tar.gz
- tar -xzf /tmp/uniget_Linux_x86_64.tar.gz -C /usr/local/bin uniget
- rm -f /tmp/uniget_Linux_x86_64.tar.gz

power_state:
  mode: reboot
  delay: now